[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "parcels"
description = "Framework for Lagrangian tracking of virtual ocean particles in the petascale age."
readme = "README.md"
dynamic = ["version"]
authors = [{name = "oceanparcels.org team"}]
requires-python = ">=3.8"
license = {file = "LICENSE.md"}
classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Operating System :: OS Independent",
  "Topic :: Scientific/Engineering",
  "Intended Audience :: Science/Research",
]
dependencies = [
  "cgen",
  "cftime",
  "numpy",
  "dask",
  "cftime",
  "psutil",
  "netCDF4",
  "zarr",
  "tqdm",
  "pymbolic",
  "pytest",
  "scipy",
  "xarray",
]

[project.urls]
homepage = "https://oceanparcels.org/"
repository = "https://github.com/OceanParcels/parcels"
Tracker = "https://github.com/OceanParcels/parcels/issues"

[tool.setuptools]
packages = ["parcels"]

[tool.setuptools.package-data]
parcels = ["parcels/include/*"]

[tool.setuptools_scm]
write_to = "parcels/_version_setup.py"
local_scheme = "no-local-version"

[tool.pytest.ini_options]
python_files = ["test_*.py", "example_*.py", "*tutorial*"]

[tool.ruff]
target-version = "py38"

[tool.ruff.lint]
exclude = ["*.ipynb"]

select = [
    "D",  # pydocstyle
    "E",  # Error
    "F",  # pyflakes
    "I",  # isort
    # "UP", # pyupgrade
]

ignore = [
    # line too long (82 > 79 characters)
    "E501",
    # ‘from module import *’ used; unable to detect undefined names
    "F403",

    # TODO: ignore for now (requires more work). Remove ignore once fixed
    # Missing docstring in public module
    "D100",
    # Missing docstring in public class
    "D101",
    # Missing docstring in public method
    "D102",
    # Missing docstring in public function
    "D103",
    # Missing docstring in public package
    "D104",
    # Missing docstring in magic method
    "D105",
    # Missing docstring in __init__
    "D400",
    # First line should be in imperative mood (requires writing of summaries)
    "D401",
    # First word of the docstring should not be `This`
    "D404",
    # 1 blank line required between summary line and description (requires writing of summaries)
    "D205",
    # do not use bare except, specify exception instead
    "E722",
]

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.format]
exclude = [
  "parcels/tools/interpolation_utils.py",

  # List of files to ignore formatting (ordered by ascending line count)
  "tests/test_mpirun.py",
  "parcels/tools/global_statics.py",
  "tests/test_tools.py",
  "parcels/gridset.py",
  "parcels/tools/timer.py",
  "parcels/application_kernels/TEOSseawaterdensity.py",
  "tests/test_particles.py",
  "parcels/application_kernels/interaction.py",
  "parcels/application_kernels/advectiondiffusion.py",
  "parcels/tools/statuscodes.py",
  "tests/test_data/create_testfields.py",
  "tests/test_diffusion.py",
  "parcels/tools/exampledata_utils.py",
  "parcels/interaction/neighborsearch/hashflat.py",
  "parcels/interaction/neighborsearch/hashspherical.py",
  "parcels/interaction/neighborsearch/basehash.py",
  "parcels/rng.py",
  "parcels/interaction/neighborsearch/base.py",
  "parcels/interaction/interactionkernel.py",
  "parcels/tools/converters.py",
  "parcels/application_kernels/advection.py",
  "parcels/particlefile.py",
  "parcels/compilation/codecompiler.py",
  "parcels/particle.py",
  "tests/test_interaction.py",
  "tests/test_particlefile.py",
  "parcels/application_kernels/EOSseawaterproperties.py",
  "tests/test_kernel_execution.py",
  "tests/test_particlesets.py",
  "parcels/particledata.py",
  "tests/test_kernel_language.py",
  "docs/conf.py",
  "parcels/grid.py",
  "tests/test_advection.py",
  "parcels/kernel.py",
  "parcels/fieldfilebuffer.py",
  "tests/test_fieldset_sampling.py",
  "parcels/compilation/codegenerator.py",
  "tests/test_grids.py",
  "parcels/particleset.py",
  "tests/test_fieldset.py",
  "parcels/fieldset.py",
  "parcels/field.py",
]
